version: '3.3'

volumes:
  static:
  media:
  pg_data:


services:

  db:
    container_name: foodgram-db
    image: postgres:13
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  foodgram_frontend:
    container_name: foodgram-front
    env_file:
      - ../.env
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  
  foodgram_backend:
    container_name: foodgram_backend
    build: ../backend/foodgram_backend
    env_file:
      - ../.env
    depends_on: 
      - db
    volumes:
      - static:/backend_static
      - media:/var/www/foodgram/media/

  foodgram-proxy:
    container_name: foodgram-proxy
    image: nginx:1.22.1
    env_file:
      - ../.env
    restart: always
    ports:
      - 8001:80
    volumes:
      - static:/staticfiles/ 
      - media:/var/www/foodgram/media/
    depends_on:
      - backend
      - frontend
